### ISSUE TITLE
Modpack won't open. 

### ISSUE THREAD

**Issue by Thatiweirdo** [WCDN-group/To-Creationist-Surrealist#2]
I downloaded the modpack on Curseforge and tried to launch it, but it just won't work. It kept saying "Exit code 0", so I tried adding more ram and redownloading it, but nothing's working. I'm really sad about this, because it looks like a really cool modpack. 

[latest.log](https://github.com/liuseniubi/CreaTech/files/6280514/latest.log)

Any idea why it won't work?

**Comment by liuseniubi** [comment]
Try to use the latest [Java 8.](https://download.oracle.com/otn/java/jdk/8u281-b09/89d678f2be164786b292527658ca1605/jre-8u281-windows-x64.exe)

**Comment by liuseniubi** [comment]
Also, thanks your playing!

**Comment by jammer131** [comment]
still will not launch modpack even with latest JDK and Java 8

https://pastebin.com/TwdqicM3

**Comment by liuseniubi** [comment]
> still will not launch modpack even with latest JDK and Java 8
> 
> https://pastebin.com/TwdqicM3

Is it a private paste? I cannot open it.

**Comment by liuseniubi** [comment]
> still will not launch modpack even with latest JDK and Java 8
> 
> https://pastebin.com/TwdqicM3

Open the Control Panel and find "Language and region" and unselect anything with “beta”, that might be helpful.

**Comment by Jdreioe** [comment]
I'm having the same issue (Java 8 291) using both MultiMC and Curse.

8 GB RAM allocated
Ryzen 7 3700X
GTX 1660 TI 
Link to my pastebin: https://paste.ee/p/ebbVJ

**Comment by liuseniubi** [comment]
> I'm having the same issue (Java 8 291) using both MultiMC and Curse.
> 
> 8 GB RAM allocated
> Ryzen 7 3700X
> GTX 1660 TI
> Link to my pastebin: https://paste.ee/p/ebbVJ

Try to reinstall it, It seems like your forge wasn't installed correctly.

**Comment by Jdreioe** [comment]
That didn't help. 

Neither on Curse or MultiMC.

**Comment by liuseniubi** [comment]
> That didn't help.
> 
> Neither on Curse or MultiMC.

I see, I'll try to fix it later. Thanks everyone!

**Comment by zeeoric** [comment]
I just copied the config, mod and script folders from your modpack into a new installation and installed forge 36.1.4 and had no issue running the modpack from the new installation.   Not sure where the issue lies, i tried updating the modpack to an updated forge of 36.1.4 but that didnt work, still exact same error

**Comment by liuseniubi** [comment]
I updated my modpack, please have a try. If it still cannot open, I have no idea to fix it. :-(

**Comment by jammer131** [comment]
https://pastebin.com/qX4i0eu6

still same issue hopefully this link works

**Comment by Famous5000** [comment]
I think I know what the problem is: Your pack is using a non-standard "!" for its title [！] which is causing major issues for those who are trying to play the pack. This is a character issue, and you need to rename the pack and push a new update out with that. I strongly suggest you rename and republish without that exclamation mark. @liuseniubi
Mentioned because I identified the problem and the solution.

**Comment by liuseniubi** [comment]
> I think I know what the problem is: Your pack is using a non-standard "!" for its title [！] which is causing major issues for those who are trying to play the pack. This is a character issue, and you need to rename the pack and push a new update out with that. I strongly suggest you rename and republish without that exclamation mark. @liuseniubi
> Mentioned because I identified the problem and the solution.

WOW! AWESOME! THANKS A LOT!

**Comment by Famous5000** [comment]
No problem, glad to be of help. After further testing, that was indeed the problem; renaming the directory **SOLVED** the problem.

**Comment by liuseniubi** [comment]
For everyone in this issue:
Sorry for everyone, I'm Chinese and we use [！] instead of [!], and that was the problem.
My team are all students, so we don't have enough spare time to update this modpack. But we are constructing a brand new developing way in the early age to replace the Exnihilo mod (Because we think it's too boring, all you have to do is sieveing things until you created a cobblestone generator.).
So, wait for next update! :)

**Comment by liuseniubi** [comment]
> No problem, glad to be of help. After further testing, that was indeed the problem; renaming the directory **SOLVED** the problem.

Could you please test it again, I've fixed it. Thanks in advance.

**Comment by Famous5000** [comment]
> > No problem, glad to be of help. After further testing, that was indeed the problem; renaming the directory **SOLVED** the problem.
> 
> Could you please test it again, I've fixed it. Thanks in advance.

Sure thing, let me download a fresh instance from the CF website, will let you know if you fixed it.

**Comment by Famous5000** [comment]
I can tell immediately by the renaming of the pack that the fix will definitely work for everyone else here. Thank you for implementing the fix so quickly.

**Comment by liuseniubi** [comment]
> I can tell immediately by the renaming of the pack that the fix will definitely work for everyone else here. Thank you for implementing the fix so quickly.

Thanks again! It's time to close that annoying issue.
